name: Deploy Firebase

on: [push]

jobs:
  deploy_firebase:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: setup
        run: |
          cd firebase && npm run setup:ci

      - name: build-dev
        if: github.ref != 'refs/heads/prod'
        run: |
          npx firebase-tools deploy -P ${{ SECRETS.FIREBASE_DEV_ENV }} --token ${{ SECRETS.FIREBASE_CI_TOKEN }}

      - name: build-prod
        if: github.ref == 'refs/heads/prod'
        run: |
          npx firebase-tools deploy -P ${{ SECRETS.FIREBASE_PROD_ENV }} --token ${{ SECRETS.FIREBASE_CI_TOKEN }}
